//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroGearsV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnteredChart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnteredChart()
        {
            this.ChartAngles = new HashSet<ChartAngle>();
            this.ChartHouses = new HashSet<ChartHouse>();
            this.ChartObjects = new HashSet<ChartObject>();
            this.RelocatedChartAngles = new HashSet<RelocatedChartAngle>();
            this.RelocatedChartHouses = new HashSet<RelocatedChartHous>();
            this.RelocatedCharts = new HashSet<RelocatedChart>();
        }
    
        public int EnteredChartId { get; set; }
        public string SubjectName { get; set; }
        public string SubjectLocation { get; set; }
        public System.DateTime OriginDateTime { get; set; }
        public byte ChartTypeId { get; set; }
        public bool OriginDateTimeUnknown { get; set; }
        public Nullable<System.DateTimeOffset> OriginDateTimeOffset { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartAngle> ChartAngles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartHouse> ChartHouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartObject> ChartObjects { get; set; }
        public virtual ChartType ChartType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelocatedChartAngle> RelocatedChartAngles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelocatedChartHous> RelocatedChartHouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelocatedChart> RelocatedCharts { get; set; }
    }
}
