//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroGearsV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseCusp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HouseCusp()
        {
            this.ChartHouses = new HashSet<ChartHouse>();
            this.RelocatedChartHouses = new HashSet<RelocatedChartHous>();
        }
    
        public byte HouseId { get; set; }
        public string HouseName { get; set; }
        public string HouseCuspName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChartHouse> ChartHouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelocatedChartHous> RelocatedChartHouses { get; set; }
    }
}
