//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstroGearsV2Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspectInterpretationType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspectInterpretationType()
        {
            this.AspectInterpretations = new HashSet<AspectInterpretation>();
            this.AspectInterpretations1 = new HashSet<AspectInterpretation>();
        }
    
        public byte AspectInterpretationTypeId { get; set; }
        public string AspectInterpretationTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspectInterpretation> AspectInterpretations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspectInterpretation> AspectInterpretations1 { get; set; }
    }
}
